# important: install python 3.9 and mono-devel
# https://www.mono-project.com/download/stable/#download-lin-debian
image: python:3.9-buster

before_script:
  - apt update
  - apt install -y apt-transport-https dirmngr gnupg ca-certificates
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb https://download.mono-project.com/repo/debian stable-buster main" > /etc/apt/sources.list.d/mono-official-stable.list
  - apt update
  - apt install -y mono-devel

test:
  stage: test
  script:
    - python -m pip install -e .[dev,simulation]
    - ./run-checks

pages:
  stage: deploy
  only:
    - master
  script:
    - python -m pip install .[docs,simulation]
    - make -C docs/ html
    - mv ./docs/_build/html ./public
  artifacts:
    paths:
      - public/
